### ISSUE TITLE
HTTP Error 413 Request entity too large when  docker container is combined with steveltn/https-portal

### ISSUE THREAD

**Issue by dc232** [emcniece/docker-wordpress#2]
Hi, 
when using these containers with steveltn/https-portal via docker compose I am getting a 413 error when uploading anything bigger than 1mb in size.
 
A lot of people have mentioned on the internet to increase the client_max_body_size in nginx, however, I can see that in the nginx conf that it is 128M. The containers themselves work perfectly without https but when https is applied via the steveltn/https-portal I am getting the error

some are saying to set the value to unlimited via client_max_body_size 0; 
for the docker file please see

any help with sorting out the error will be greatly appreciated

**Comment by dc232** [comment]
Hi, seems not to be this container turns out I misread the docs and the https portal by default has a client_max_body_size of 1, bad I know but seems to be changeable also thanks for making such awesome docker containers

**Comment by emcniece** [comment]
Yes, as you have discovered the `client_max_body_size` parameter must be set for _all_ Nginx instances in the chain. If you are using the [Nginx instance in the docker-compose file](https://github.com/emcniece/docker-wordpress/blob/master/docker-compose.yml#L6) here, it sets `client_max_body_size` in [wp-nginx.conf](https://github.com/emcniece/docker-wordpress/blob/master/wp-nginx.conf)... but you will have to find a way to apply this to any proxy in front of this container too.
